name: Deploy bugglights.com

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, bugg-lights]

    defaults:
      run:
        working-directory: /var/www/bugg-lights

    steps:
      - name: Stop PM2 process
        run: pm2 stop bugg-lights || echo "PM2 process not running, continuing"

      - name: Update repository
        run: |
          git fetch origin
          git checkout main
          git reset --hard ${{ github.sha }}

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Restart PM2 process
        run: |
          pm2 start bugg-lights
          pm2 save
